name: Simple HTML/CSS CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (Optional, for a simple test environment)
        uses: actions/setup-node@v3
        with:
          node-version: '16'  

      - name: Check that index.html and styles.css exist
        run: |
          test -f index.html
          test -f styles.css

      - name: Build and deploy (Optional)
        run: echo "No build process, only a simple static site"
